;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Test6.Fireball.Burn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Test6.Fireball.Impact",DevComment="")
+GameplayTagList=(Tag="GAS.Data.FireballDamage",DevComment="")
+GameplayTagList=(Tag="GAS.TEST6.Ability.Fireball.Cooldown",DevComment="")
+GameplayTagList=(Tag="GAS.TEST6.Debuff.Burn",DevComment="")

